/**
 * Game data: Characters, Cards, Enemies, Rooms
 */

const GameData = {
  // Character definitions
  characters: [
    {
      id: CONSTANTS.CHARACTER_IDS.JACK,
      name: "Jack O'Neill",
      shortName: 'Jack',
      maxHealth: 10,
      deck: CONSTANTS.CHARACTER_IDS.JACK,
    },
    {
      id: CONSTANTS.CHARACTER_IDS.SAM,
      name: 'Samantha Carter',
      shortName: 'Sam',
      maxHealth: 8,
      deck: CONSTANTS.CHARACTER_IDS.SAM,
    },
    {
      id: CONSTANTS.CHARACTER_IDS.DANIEL,
      name: 'Daniel Jackson',
      shortName: 'Daniel',
      maxHealth: 7,
      deck: CONSTANTS.CHARACTER_IDS.DANIEL,
    },
    {
      id: CONSTANTS.CHARACTER_IDS.TEALC,
      name: "Teal'c",
      shortName: "Teal'c",
      maxHealth: 12,
      deck: CONSTANTS.CHARACTER_IDS.TEALC,
    },
  ],

  // Card decks
  cards: {
    [CONSTANTS.CHARACTER_IDS.JACK]: [
      {
        id: 'jack_01',
        name: 'Suppressing Fire',
        initiative: 35,
        top: { type: 'attack', value: 3, range: 2, push: 1, text: 'Attack 3, Range 2, Push 1' },
        bottom: { type: 'move', value: 3, text: 'Move 3' },
      },
      {
        id: 'jack_02',
        name: 'Tactical Position',
        initiative: 45,
        top: { type: 'move', value: 4, text: 'Move 4' },
        bottom: { type: 'buff', value: 1, text: 'Ally +1 Attack' },
      },
      {
        id: 'jack_03',
        name: 'P90 Burst',
        initiative: 25,
        top: { type: 'attack', value: 4, range: 3, text: 'Attack 4, Range 3' },
        bottom: { type: 'move', value: 2, text: 'Move 2' },
      },
      {
        id: 'jack_04',
        name: 'Fall Back',
        initiative: 18,
        top: { type: 'move', value: 3, text: 'Move 3' },
        bottom: { type: 'special', text: 'All allies Move 2' },
      },
      {
        id: 'jack_05',
        name: 'Grenade',
        initiative: 55,
        top: { type: 'attack', value: 2, range: 3, aoe: true, text: 'Attack 2, Range 3, AOE' },
        bottom: { type: 'move', value: 3, text: 'Move 3' },
      },
      {
        id: 'jack_06',
        name: 'Cover Fire',
        initiative: 30,
        top: { type: 'attack', value: 3, range: 2, text: 'Attack 3, Range 2' },
        bottom: { type: 'move', value: 4, text: 'Move 4' },
      },
      {
        id: 'jack_07',
        name: 'Tactical Advance',
        initiative: 40,
        top: { type: 'move', value: 5, text: 'Move 5' },
        bottom: { type: 'attack', value: 2, range: 1, text: 'Attack 2' },
      },
      {
        id: 'jack_08',
        name: 'Headshot',
        initiative: 60,
        top: { type: 'attack', value: 5, range: 3, text: 'Attack 5, Range 3' },
        bottom: { type: 'move', value: 2, text: 'Move 2' },
      },
      {
        id: 'jack_09',
        name: 'Regroup',
        initiative: 20,
        top: { type: 'move', value: 3, text: 'Move 3' },
        bottom: { type: 'heal', value: 2, text: 'Heal 2 (self)' },
      },
      {
        id: 'jack_10',
        name: 'Suppressive Fire',
        initiative: 50,
        top: { type: 'attack', value: 3, range: 3, text: 'Attack 3, Range 3' },
        bottom: { type: 'move', value: 3, text: 'Move 3' },
      },
    ],

    [CONSTANTS.CHARACTER_IDS.SAM]: [
      {
        id: 'sam_01',
        name: 'Zat Gun',
        initiative: 28,
        top: { type: 'attack', value: 2, range: 2, stun: true, text: 'Attack 2, Range 2, Stun' },
        bottom: { type: 'move', value: 3, text: 'Move 3' },
      },
      {
        id: 'sam_02',
        name: 'Tech Analysis',
        initiative: 15,
        top: { type: 'buff', text: 'Ally gains Advantage' },
        bottom: { type: 'move', value: 2, text: 'Move 2' },
      },
      {
        id: 'sam_03',
        name: 'C4 Placement',
        initiative: 65,
        top: { type: 'trap', value: 4, text: 'Set trap: 4 damage' },
        bottom: { type: 'move', value: 3, text: 'Move 3' },
      },
      {
        id: 'sam_04',
        name: 'Shield Modulation',
        initiative: 12,
        top: { type: 'shield', value: 2, text: 'Ally gains Shield 2' },
        bottom: { type: 'move', value: 3, text: 'Move 3' },
      },
      {
        id: 'sam_05',
        name: 'Covering Fire',
        initiative: 38,
        top: { type: 'attack', value: 3, range: 4, text: 'Attack 3, Range 4' },
        bottom: { type: 'move', value: 2, text: 'Move 2' },
      },
      {
        id: 'sam_06',
        name: 'Field Repair',
        initiative: 22,
        top: { type: 'heal', value: 3, range: 2, text: 'Heal 3, Range 2' },
        bottom: { type: 'move', value: 3, text: 'Move 3' },
      },
      {
        id: 'sam_07',
        name: 'Precise Shot',
        initiative: 45,
        top: { type: 'attack', value: 4, range: 3, text: 'Attack 4, Range 3' },
        bottom: { type: 'move', value: 2, text: 'Move 2' },
      },
      {
        id: 'sam_08',
        name: 'Naquadah Reactor',
        initiative: 18,
        top: { type: 'special', text: 'Draw 2 cards' },
        bottom: { type: 'move', value: 3, text: 'Move 3' },
      },
      {
        id: 'sam_09',
        name: 'Tactical Retreat',
        initiative: 10,
        top: { type: 'move', value: 5, text: 'Move 5' },
        bottom: { type: 'shield', value: 1, text: 'Shield 1 (self)' },
      },
      {
        id: 'sam_10',
        name: 'Sustained Fire',
        initiative: 42,
        top: { type: 'attack', value: 3, range: 3, text: 'Attack 3, Range 3' },
        bottom: { type: 'move', value: 3, text: 'Move 3' },
      },
    ],

    [CONSTANTS.CHARACTER_IDS.DANIEL]: [
      {
        id: 'daniel_01',
        name: 'Field Medicine',
        initiative: 20,
        top: { type: 'heal', value: 3, range: 2, text: 'Heal 3, Range 2' },
        bottom: { type: 'move', value: 3, text: 'Move 3' },
      },
      {
        id: 'daniel_02',
        name: 'Ancient Knowledge',
        initiative: 8,
        top: { type: 'special', text: 'Draw 2 cards' },
        bottom: { type: 'move', value: 2, text: 'Move 2' },
      },
      {
        id: 'daniel_03',
        name: 'Distraction',
        initiative: 14,
        top: { type: 'push', value: 2, text: 'Push enemy 2' },
        bottom: { type: 'move', value: 3, text: 'Move 3' },
      },
      {
        id: 'daniel_04',
        name: 'Defensive Shot',
        initiative: 32,
        top: { type: 'attack', value: 2, range: 2, text: 'Attack 2, Range 2' },
        bottom: { type: 'shield', value: 1, text: 'Shield 1 (self)' },
      },
      {
        id: 'daniel_05',
        name: 'Inspiring Words',
        initiative: 25,
        top: { type: 'heal', value: 1, aoe: true, text: 'All allies Heal 1' },
        bottom: { type: 'move', value: 3, text: 'Move 3' },
      },
      {
        id: 'daniel_06',
        name: 'Peaceful Resolution',
        initiative: 5,
        top: { type: 'special', text: 'Enemy skips turn' },
        bottom: { type: 'move', value: 4, text: 'Move 4' },
      },
      {
        id: 'daniel_07',
        name: 'Careful Aim',
        initiative: 48,
        top: { type: 'attack', value: 3, range: 3, text: 'Attack 3, Range 3' },
        bottom: { type: 'move', value: 2, text: 'Move 2' },
      },
      {
        id: 'daniel_08',
        name: 'Emergency Heal',
        initiative: 16,
        top: { type: 'heal', value: 4, text: 'Heal 4 (self or ally)' },
        bottom: { type: 'move', value: 2, text: 'Move 2' },
      },
      {
        id: 'daniel_09',
        name: 'Evasive Action',
        initiative: 12,
        top: { type: 'move', value: 5, text: 'Move 5' },
        bottom: { type: 'shield', value: 2, text: 'Shield 2 (self)' },
      },
      {
        id: 'daniel_10',
        name: 'Supporting Fire',
        initiative: 35,
        top: { type: 'attack', value: 2, range: 3, text: 'Attack 2, Range 3' },
        bottom: { type: 'heal', value: 2, text: 'Heal 2 (ally)' },
      },
    ],

    [CONSTANTS.CHARACTER_IDS.TEALC]: [
      {
        id: 'tealc_01',
        name: 'Staff Blast',
        initiative: 42,
        top: { type: 'attack', value: 4, range: 2, text: 'Attack 4, Range 2' },
        bottom: { type: 'move', value: 2, text: 'Move 2' },
      },
      {
        id: 'tealc_02',
        name: 'Indeed',
        initiative: 55,
        top: { type: 'attack', value: 5, range: 1, text: 'Attack 5, Melee' },
        bottom: { type: 'move', value: 3, text: 'Move 3' },
      },
      {
        id: 'tealc_03',
        name: 'Jaffa Training',
        initiative: 28,
        top: { type: 'move', value: 3, text: 'Move 3' },
        bottom: { type: 'shield', value: 2, text: 'Shield 2 (self)' },
      },
      {
        id: 'tealc_04',
        name: "Kel'no'reem",
        initiative: 10,
        top: { type: 'heal', value: 2, text: 'Heal 2 (self)' },
        bottom: { type: 'special', text: 'Cannot be damaged' },
      },
      {
        id: 'tealc_05',
        name: 'Cleaving Strike',
        initiative: 48,
        top: { type: 'attack', value: 3, aoe: true, text: 'Attack 3, hit 2 adjacent' },
        bottom: { type: 'move', value: 2, text: 'Move 2' },
      },
      {
        id: 'tealc_06',
        name: 'Warrior Stance',
        initiative: 15,
        top: { type: 'shield', value: 3, text: 'Shield 3 (self)' },
        bottom: { type: 'move', value: 2, text: 'Move 2' },
      },
      {
        id: 'tealc_07',
        name: 'Charge',
        initiative: 38,
        top: { type: 'move', value: 4, text: 'Move 4' },
        bottom: { type: 'attack', value: 3, range: 1, text: 'Attack 3' },
      },
      {
        id: 'tealc_08',
        name: 'Power Strike',
        initiative: 62,
        top: { type: 'attack', value: 6, range: 1, text: 'Attack 6, Melee' },
        bottom: { type: 'move', value: 2, text: 'Move 2' },
      },
      {
        id: 'tealc_09',
        name: 'Defensive Position',
        initiative: 20,
        top: { type: 'shield', value: 2, text: 'Shield 2 (self)' },
        bottom: { type: 'move', value: 3, text: 'Move 3' },
      },
      {
        id: 'tealc_10',
        name: 'Staff Sweep',
        initiative: 45,
        top: { type: 'attack', value: 3, range: 2, text: 'Attack 3, Range 2' },
        bottom: { type: 'move', value: 3, text: 'Move 3' },
      },
    ],
  },

  // Enemy definitions
  enemies: {
    [CONSTANTS.ENEMY_IDS.JAFFA_WARRIOR]: {
      name: 'Jaffa Warrior',
      maxHealth: 6,
      move: 2,
      attack: 3,
      range: 1,
      ai: CONSTANTS.AI_TYPES.MELEE,
    },

    [CONSTANTS.ENEMY_IDS.JAFFA_SERPENT_GUARD]: {
      name: 'Serpent Guard',
      maxHealth: 10,
      move: 3,
      attack: 4,
      range: 2,
      ai: CONSTANTS.AI_TYPES.RANGED,
    },
  },

  // Room definitions
  rooms: [
    {
      id: 1,
      name: 'Stargate Arrival',
      width: 7,
      height: 7,
      startPositions: [
        { q: 0, r: 0 },
        { q: 1, r: 0 },
        { q: 0, r: 1 },
        { q: 1, r: 1 },
      ],
      enemies: [
        { type: CONSTANTS.ENEMY_IDS.JAFFA_WARRIOR, position: { q: 5, r: 3 } },
        { type: CONSTANTS.ENEMY_IDS.JAFFA_WARRIOR, position: { q: 4, r: 4 } },
        { type: CONSTANTS.ENEMY_IDS.JAFFA_WARRIOR, position: { q: 6, r: 3 } },
        { type: CONSTANTS.ENEMY_IDS.JAFFA_WARRIOR, position: { q: 5, r: 5 } },
      ],
      walls: [
        // Define wall hexes (perimeter)
      ],
    },
    {
      id: 2,
      name: 'Temple Corridor',
      width: 8,
      height: 6,
      startPositions: [
        { q: 0, r: 0 },
        { q: 1, r: 0 },
        { q: 0, r: 1 },
        { q: 1, r: 1 },
      ],
      enemies: [
        { type: CONSTANTS.ENEMY_IDS.JAFFA_WARRIOR, position: { q: 5, r: 2 } },
        { type: CONSTANTS.ENEMY_IDS.JAFFA_WARRIOR, position: { q: 6, r: 3 } },
        { type: CONSTANTS.ENEMY_IDS.JAFFA_WARRIOR, position: { q: 5, r: 4 } },
        { type: CONSTANTS.ENEMY_IDS.JAFFA_WARRIOR, position: { q: 7, r: 2 } },
        { type: CONSTANTS.ENEMY_IDS.JAFFA_SERPENT_GUARD, position: { q: 6, r: 4 } },
      ],
      walls: [],
    },
    {
      id: 3,
      name: 'Artifact Chamber',
      width: 9,
      height: 8,
      startPositions: [
        { q: 0, r: 0 },
        { q: 1, r: 0 },
        { q: 0, r: 1 },
        { q: 1, r: 1 },
      ],
      enemies: [
        { type: CONSTANTS.ENEMY_IDS.JAFFA_WARRIOR, position: { q: 6, r: 3 } },
        { type: CONSTANTS.ENEMY_IDS.JAFFA_WARRIOR, position: { q: 7, r: 4 } },
        { type: CONSTANTS.ENEMY_IDS.JAFFA_WARRIOR, position: { q: 6, r: 5 } },
        { type: CONSTANTS.ENEMY_IDS.JAFFA_WARRIOR, position: { q: 8, r: 4 } },
        { type: CONSTANTS.ENEMY_IDS.JAFFA_SERPENT_GUARD, position: { q: 7, r: 6 } },
      ],
      artifactPosition: { q: 7, r: 5 },
      walls: [],
    },
  ],
};
